// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOZS0A_xN_4Btmi05eKEuwYHlOGbe6hq8',
    appId: '1:164056244939:web:c828a1b88ccb45692bf14e',
    messagingSenderId: '164056244939',
    projectId: 'driving-school-project-c7918',
    authDomain: 'driving-school-project-c7918.firebaseapp.com',
    storageBucket: 'driving-school-project-c7918.firebasestorage.app',
    measurementId: 'G-9RMG0D97C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxEumZqyqdHoR1dJKL5y0o_nUj_2AXGjc',
    appId: '1:164056244939:android:750cc7bb700896632bf14e',
    messagingSenderId: '164056244939',
    projectId: 'driving-school-project-c7918',
    storageBucket: 'driving-school-project-c7918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSRRBDgtwyBp3bwHfbzGlIZDEMOw57z4M',
    appId: '1:164056244939:ios:639c83b6c25c8c112bf14e',
    messagingSenderId: '164056244939',
    projectId: 'driving-school-project-c7918',
    storageBucket: 'driving-school-project-c7918.firebasestorage.app',
    iosBundleId: 'com.example.drivingSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSRRBDgtwyBp3bwHfbzGlIZDEMOw57z4M',
    appId: '1:164056244939:ios:639c83b6c25c8c112bf14e',
    messagingSenderId: '164056244939',
    projectId: 'driving-school-project-c7918',
    storageBucket: 'driving-school-project-c7918.firebasestorage.app',
    iosBundleId: 'com.example.drivingSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOZS0A_xN_4Btmi05eKEuwYHlOGbe6hq8',
    appId: '1:164056244939:web:f2125adde8fea2cf2bf14e',
    messagingSenderId: '164056244939',
    projectId: 'driving-school-project-c7918',
    authDomain: 'driving-school-project-c7918.firebaseapp.com',
    storageBucket: 'driving-school-project-c7918.firebasestorage.app',
    measurementId: 'G-23THPZY27E',
  );
}
